<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="8" failures="0" skipped="0" tests="8" time="3.546" timestamp="2025-02-04T12:22:07.409260-08:00" hostname="hutchinson-MacBook-Pro"><testcase classname="" name="tests.agent" time="0.000"><error message="collection failure">../../.pyenv/versions/3.11.9/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
&lt;frozen importlib._bootstrap&gt;:1204: in _gcd_import
    ???
&lt;frozen importlib._bootstrap&gt;:1176: in _find_and_load
    ???
&lt;frozen importlib._bootstrap&gt;:1147: in _find_and_load_unlocked
    ???
&lt;frozen importlib._bootstrap&gt;:690: in _load_unlocked
    ???
../../Library/Caches/pypoetry/virtualenvs/great-expectations-cloud-nXW7V_tf-py3.11/lib/python3.11/site-packages/_pytest/assertion/rewrite.py:184: in exec_module
    exec(co, module.__dict__)
tests/agent/conftest.py:18: in &lt;module&gt;
    from great_expectations_cloud.agent.actions.agent_action import ActionResult, AgentAction
great_expectations_cloud/__init__.py:3: in &lt;module&gt;
    from great_expectations_cloud.agent.agent import GXAgent
great_expectations_cloud/agent/__init__.py:3: in &lt;module&gt;
    import great_expectations_cloud.agent.actions  # import actions to register them
great_expectations_cloud/agent/actions/__init__.py:3: in &lt;module&gt;
    from great_expectations_cloud.agent.actions.agent_action import (
great_expectations_cloud/agent/actions/agent_action.py:11: in &lt;module&gt;
    from great_expectations_cloud.agent.models import CreatedResource, Event
great_expectations_cloud/agent/models.py:8: in &lt;module&gt;
    from great_expectations.expectations.metadata_types import DataQualityIssues
E   ModuleNotFoundError: No module named 'great_expectations.expectations.metadata_types'</error></testcase><testcase classname="" name="tests.integration.actions.test_checkpoint_action" time="0.000"><error message="collection failure">ImportError while importing test module '/Users/hutchinson/gx/cloud/tests/integration/actions/test_checkpoint_action.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../.pyenv/versions/3.11.9/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/integration/actions/test_checkpoint_action.py:9: in &lt;module&gt;
    from great_expectations_cloud.agent.models import (
great_expectations_cloud/__init__.py:3: in &lt;module&gt;
    from great_expectations_cloud.agent.agent import GXAgent
great_expectations_cloud/agent/__init__.py:3: in &lt;module&gt;
    import great_expectations_cloud.agent.actions  # import actions to register them
great_expectations_cloud/agent/actions/__init__.py:3: in &lt;module&gt;
    from great_expectations_cloud.agent.actions.agent_action import (
great_expectations_cloud/agent/actions/agent_action.py:11: in &lt;module&gt;
    from great_expectations_cloud.agent.models import CreatedResource, Event
great_expectations_cloud/agent/models.py:8: in &lt;module&gt;
    from great_expectations.expectations.metadata_types import DataQualityIssues
E   ModuleNotFoundError: No module named 'great_expectations.expectations.metadata_types'</error></testcase><testcase classname="" name="tests.integration.actions.test_draft_datasource_config_action" time="0.000"><error message="collection failure">ImportError while importing test module '/Users/hutchinson/gx/cloud/tests/integration/actions/test_draft_datasource_config_action.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../.pyenv/versions/3.11.9/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/integration/actions/test_draft_datasource_config_action.py:8: in &lt;module&gt;
    from great_expectations_cloud.agent.actions import DraftDatasourceConfigAction
great_expectations_cloud/__init__.py:3: in &lt;module&gt;
    from great_expectations_cloud.agent.agent import GXAgent
great_expectations_cloud/agent/__init__.py:3: in &lt;module&gt;
    import great_expectations_cloud.agent.actions  # import actions to register them
great_expectations_cloud/agent/actions/__init__.py:3: in &lt;module&gt;
    from great_expectations_cloud.agent.actions.agent_action import (
great_expectations_cloud/agent/actions/agent_action.py:11: in &lt;module&gt;
    from great_expectations_cloud.agent.models import CreatedResource, Event
great_expectations_cloud/agent/models.py:8: in &lt;module&gt;
    from great_expectations.expectations.metadata_types import DataQualityIssues
E   ModuleNotFoundError: No module named 'great_expectations.expectations.metadata_types'</error></testcase><testcase classname="" name="tests.integration.actions.test_generate_data_quality_check_expectations" time="0.000"><error message="collection failure">ImportError while importing test module '/Users/hutchinson/gx/cloud/tests/integration/actions/test_generate_data_quality_check_expectations.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../.pyenv/versions/3.11.9/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/integration/actions/test_generate_data_quality_check_expectations.py:10: in &lt;module&gt;
    from great_expectations.expectations.metadata_types import DataQualityIssues
E   ModuleNotFoundError: No module named 'great_expectations.expectations.metadata_types'</error></testcase><testcase classname="" name="tests.integration.actions.test_list_table_names" time="0.000"><error message="collection failure">ImportError while importing test module '/Users/hutchinson/gx/cloud/tests/integration/actions/test_list_table_names.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../.pyenv/versions/3.11.9/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/integration/actions/test_list_table_names.py:8: in &lt;module&gt;
    from great_expectations_cloud.agent.actions import ListTableNamesAction
great_expectations_cloud/__init__.py:3: in &lt;module&gt;
    from great_expectations_cloud.agent.agent import GXAgent
great_expectations_cloud/agent/__init__.py:3: in &lt;module&gt;
    import great_expectations_cloud.agent.actions  # import actions to register them
great_expectations_cloud/agent/actions/__init__.py:3: in &lt;module&gt;
    from great_expectations_cloud.agent.actions.agent_action import (
great_expectations_cloud/agent/actions/agent_action.py:11: in &lt;module&gt;
    from great_expectations_cloud.agent.models import CreatedResource, Event
great_expectations_cloud/agent/models.py:8: in &lt;module&gt;
    from great_expectations.expectations.metadata_types import DataQualityIssues
E   ModuleNotFoundError: No module named 'great_expectations.expectations.metadata_types'</error></testcase><testcase classname="" name="tests.integration.actions.test_metric_list_action" time="0.000"><error message="collection failure">ImportError while importing test module '/Users/hutchinson/gx/cloud/tests/integration/actions/test_metric_list_action.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../.pyenv/versions/3.11.9/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/integration/actions/test_metric_list_action.py:11: in &lt;module&gt;
    from great_expectations_cloud.agent.actions import MetricListAction
great_expectations_cloud/__init__.py:3: in &lt;module&gt;
    from great_expectations_cloud.agent.agent import GXAgent
great_expectations_cloud/agent/__init__.py:3: in &lt;module&gt;
    import great_expectations_cloud.agent.actions  # import actions to register them
great_expectations_cloud/agent/actions/__init__.py:3: in &lt;module&gt;
    from great_expectations_cloud.agent.actions.agent_action import (
great_expectations_cloud/agent/actions/agent_action.py:11: in &lt;module&gt;
    from great_expectations_cloud.agent.models import CreatedResource, Event
great_expectations_cloud/agent/models.py:8: in &lt;module&gt;
    from great_expectations.expectations.metadata_types import DataQualityIssues
E   ModuleNotFoundError: No module named 'great_expectations.expectations.metadata_types'</error></testcase><testcase classname="" name="tests.integration.actions.test_run_scheduled_checkpoint" time="0.000"><error message="collection failure">ImportError while importing test module '/Users/hutchinson/gx/cloud/tests/integration/actions/test_run_scheduled_checkpoint.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../.pyenv/versions/3.11.9/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/integration/actions/test_run_scheduled_checkpoint.py:9: in &lt;module&gt;
    from great_expectations_cloud.agent.models import (
great_expectations_cloud/__init__.py:3: in &lt;module&gt;
    from great_expectations_cloud.agent.agent import GXAgent
great_expectations_cloud/agent/__init__.py:3: in &lt;module&gt;
    import great_expectations_cloud.agent.actions  # import actions to register them
great_expectations_cloud/agent/actions/__init__.py:3: in &lt;module&gt;
    from great_expectations_cloud.agent.actions.agent_action import (
great_expectations_cloud/agent/actions/agent_action.py:11: in &lt;module&gt;
    from great_expectations_cloud.agent.models import CreatedResource, Event
great_expectations_cloud/agent/models.py:8: in &lt;module&gt;
    from great_expectations.expectations.metadata_types import DataQualityIssues
E   ModuleNotFoundError: No module named 'great_expectations.expectations.metadata_types'</error></testcase><testcase classname="" name="tests.test_logging_cfg" time="0.000"><error message="collection failure">ImportError while importing test module '/Users/hutchinson/gx/cloud/tests/test_logging_cfg.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../.pyenv/versions/3.11.9/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_logging_cfg.py:14: in &lt;module&gt;
    from great_expectations_cloud.logging.logging_cfg import (
great_expectations_cloud/__init__.py:3: in &lt;module&gt;
    from great_expectations_cloud.agent.agent import GXAgent
great_expectations_cloud/agent/__init__.py:3: in &lt;module&gt;
    import great_expectations_cloud.agent.actions  # import actions to register them
great_expectations_cloud/agent/actions/__init__.py:3: in &lt;module&gt;
    from great_expectations_cloud.agent.actions.agent_action import (
great_expectations_cloud/agent/actions/agent_action.py:11: in &lt;module&gt;
    from great_expectations_cloud.agent.models import CreatedResource, Event
great_expectations_cloud/agent/models.py:8: in &lt;module&gt;
    from great_expectations.expectations.metadata_types import DataQualityIssues
E   ModuleNotFoundError: No module named 'great_expectations.expectations.metadata_types'</error></testcase></testsuite></testsuites>
